-- Project schema init
CREATE TABLE IF NOT EXISTS roles (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(64) NOT NULL,
	PRIMARY KEY (id))
	
CREATE TABLE IF NOT EXISTS users (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	credentials VARCHAR(128) NOT NULL,
	name VARCHAR(64) NOT NULL,
	role INT UNSIGNED NOT NULL,
	PRIMARY KEY (id),
	INDEX role_idx (role ASC),
	CONSTRAINT role
		FOREIGN KEY (role)
		REFERENCES roles (id)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION)
		
CREATE TABLE IF NOT EXISTS labels (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(64) NOT NULL,
	PRIMARY KEY (id))
	
CREATE TABLE IF NOT EXISTS releases (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	description VARCHAR(64) NOT NULL,
	start_date DATE NOT NULL,
	end_date DATE NOT NULL,
	PRIMARY KEY (id))
	
CREATE TABLE IF NOT EXISTS sprints (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	description VARCHAR(64) NOT NULL,
	start_date DATE NOT NULL,
	end_date DATE NOT NULL,
	PRIMARY KEY (id))
	
CREATE TABLE IF NOT EXISTS tasks (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	label INT UNSIGNED NOT NULL,
	description VARCHAR(256) NOT NULL,
	hours_left TINYINT NOT NULL,
	release_num INT UNSIGNED NULL,
	sprint INT UNSIGNED NULL,
	PRIMARY KEY (id),
	INDEX label_idx (label ASC),
	INDEX release_idx (release_num ASC),
	INDEX sprint_idx (sprint ASC),
	CONSTRAINT label
		FOREIGN KEY (label)
		REFERENCES labels (id)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
	CONSTRAINT release_num
		FOREIGN KEY (release_num)
		REFERENCES releases (id)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
	CONSTRAINT sprint
		FOREIGN KEY (sprint)
		REFERENCES sprints (id)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION)
		
CREATE TABLE IF NOT EXISTS issues (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	task INT UNSIGNED NOT NULL,
	description VARCHAR(256) NOT NULL,
	is_open BIT(1) NOT NULL,
	PRIMARY KEY (id),
	INDEX task_idx (task ASC),
	CONSTRAINT task
		FOREIGN KEY (task)
		REFERENCES tasks (id)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION)
		
CREATE TABLE IF NOT EXISTS project (
	name VARCHAR(64) NOT NULL,
	description VARCHAR(256) NULL,
	PRIMARY KEY (name))